### ISSUE TITLE
Johnson-Neyman technique with multilevel equations

### ISSUE THREAD

**Issue by seonghobae** [jacob-long/jtools#11]
Hi,

I happy to meet this amazing library to run Johnson-Neyman makes easily.

However, I have a trouble to run in multilevel equations.

Here is the pseudo code:

```R
  library('lme4')
  modJN1 <- glmer(IMP ~ ACQ + DEF + (ACQ+DEF|teamid) + RADIC + INCRE +
                    RADIC:ACQ + RADIC:DEF + INCRE:ACQ + INCRE:DEF,
                  data = rawSEM_recursive, REML = T)
  sim_slopes(modJN1, pred = RADIC, modx = ACQ, jnplot = TRUE)
```

As the result, I got the negative hessian error messages. If I have to make a Johnson-Neyman with Multilevel equations, What I have to do?

Best,
Seongho

**Comment by seonghobae** [comment]
Here is a error messages

```R
> sim_slopes(modJN1, pred = RADIC, modx = ACQ, jnplot = TRUE)
Error in jns[[1]]$plot : $ operator is invalid for atomic vectors
추가정보: 경고메시지(들): 
1: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  unable to evaluate scaled gradient
2: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge: degenerate  Hessian with 1 negative eigenvalues
```

**Comment by seonghobae** [comment]
I tried to calibrate without the random effect, however, it fails again.

```R
> modJN2 <- glmer(IMP ~ ACQ + DEF + RADIC + INCRE + RADIC:ACQ + RADIC:DEF + INCRE:ACQ + INCRE:DEF, data = rawSEM_recursive, REML = F)
에러: No random effects terms specified in formula
추가정보: 경고메시지(들): 
In glmer(IMP ~ ACQ + DEF + RADIC + INCRE + RADIC:ACQ + RADIC:DEF +  :
  calling glmer() with family=gaussian (identity link) as a shortcut to lmer() is deprecated; please call lmer() directly
> sim_slopes(modJN2, pred = RADIC, modx = ACQ, jnplot = TRUE)
에러: $ operator is invalid for atomic vectors
추가정보: 경고메시지(들): 
1: In pp$ptr() : restarting interrupted promise evaluation
2: In pp$ptr() : internal error -3 in R_decompress1
3: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  unable to evaluate scaled gradient
4: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge: degenerate  Hessian with 1 negative eigenvalues
5: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  unable to evaluate scaled gradient
6: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge: degenerate  Hessian with 1 negative eigenvalues
```

**Comment by jacob-long** [comment]
I haven't been able to replicate this particular error, but in general I had not tested johnson_neyman with mixed models. I just published an update with a few tweaks that should add compatibility, but in my testing I never generated these convergence errors so I can't be sure where they come from/if they were fixed.

To see if the latest update fixed this, install the development version from Github:

```r
install.packages("devtools")
devtools::install_github("jacob-long/jtools")
```

**Comment by seonghobae** [comment]
Okay, cool! I've check out your work. ```jtools::johnson_neyman``` is works. That's useful to me. However, I also need to get results from 'sim__slopes'. Could you Have any ideas to get results of simple slopes in sim_slopes even that is trick?

```R
> jtools::johnson_neyman(mod1_3_freq,  pred = RADIC, modx = DEF)
JOHNSON-NEYMAN INTERVAL

The slope of RADIC is p < .05 when DEF is INSIDE this interval:
[-4.41, -0.34]
Note: The range of observed values of DEF is [-1.81, 2.62]
> jtools::sim_slopes(mod1_3_freq,  pred = RADIC, modx = DEF)
Error: $ operator is invalid for atomic vectors
```

Best,
Seongho

**Comment by jacob-long** [comment]
Hello Seongho, I believe I've fixed this bug. Please download the latest Github version and let me know if it's working for you.

**Comment by seonghobae** [comment]
ICC 구해 봤는데 공변인 넣으니까 상당히 커지더라구요... 자세한 건 있다가 보시죠!

Seongho Bae
PsyD candidate in applied psychological measurement and assessment for high-stakes personnel decisions
+82-70-7578-2537 | +82-10-2571-7587
seongho@kw.ac.kr

2018. 1. 26. 오전 9:52, Jacob Long <notifications@github.com> 작성:

**Comment by seonghobae** [comment]
Okay, I installed new version but I still have a trouble to run.
```R
> modSimSlope1 <- jtools::sim_slopes(mod1_lme, pred = RADIC, modx = ACQ)
경고메시지(들): 
1: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  unable to evaluate scaled gradient
2: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge: degenerate  Hessian with 3 negative eigenvalues
3: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  unable to evaluate scaled gradient
4: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge: degenerate  Hessian with 1 negative eigenvalues
5: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  unable to evaluate scaled gradient
6: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge: degenerate  Hessian with 1 negative eigenvalues
7: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  unable to evaluate scaled gradient
8: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge: degenerate  Hessian with 2 negative eigenvalues
```

**Comment by seonghobae** [comment]
Oh, I did it. lmer object cut the simple_slope test. However, glmer object is works!

**Comment by seonghobae** [comment]
Finally, I changed optimiser settings. It works! Thanks, Jacob!

Best,
Seongho

**Comment by rnorouzian** [comment]
It would be great if the package could possibly accept `me()`  models from the `library(nlme)` as well, any plans to include that?
